### ISSUE TITLE
ヘッダの余剰部分

### ISSUE THREAD

**Issue by syohex** [naoya/HBFav2#125]
![2015-01-19 15 21 00](https://cloud.githubusercontent.com/assets/554281/5812180/c387c552-a0a7-11e4-87e7-f71a4fad933e.png)

iPad mini 2で利用しているのですが, ヘッダ(?)の余剰部分(赤線で囲った部分)が広く感じます.
[iPhone版のスクリーンショット](http://hbfav.bloghackers.net/)ではそのような風になっていないようです.

この余白がなければメイン部に 1, 2行多く表示できてより良く利用できるのはないかと思います.

**Comment by naoya** [comment]
おや、なるほど

iPad は気にしてなかったですが、なんでしょうね。みてみます

**Comment by Watson1978** [comment]
#131 で iPad がサポートされます。
