### ISSUE TITLE
[Pending] 特定のアカウントに通知が来ない

### ISSUE THREAD

**Issue by masutaka** [naoya/HBFav2#126]
私の環境限定ですが、通知が来なくなって困っています。
調査していただくことは可能でしょうか？

## 環境

* iPhone5s
* iOS 8.1.2
* HBFav 2.8.1

## 現象

* 1/9から私のアカウントmasutaka26で「お気に入りユーザーによるブックマーク追加」が通知センターに通知されなくなった
* 「(自分の)ブックマークの追加」「はてなスター受け取り」は通知センターに通知される

## こちらで試したこと

* ホームボタンのダブルクリックからHBFavを終了して再度起動
    * 効果なし
* iPhoneの再起動
    * 効果なし
* WebHookキーを作りなおして再設定
    * 効果なし
* iPhoneの復元
    * 効果なし
* 知人のHBFavの「はてなアカウント」をmasutaka26に変更。WebHookキーも私のものを設定
    * 通知されない。私の環境要因ではなさそう。
* 私のHBFavの「はてなアカウント」を知人のアカウントに変更。WebHookキーも知人に教えてもらい設定
    * **「お気に入りユーザーによるブックマーク追加」が通知センターに来た！**

プッシュ通知は今も
はてブ本体 → push.hbfav.com → Parse → APNサーバ → iPhone
という流れで来るのだとすると、

masutaka26のプッシュ通知がAPNサーバから来ていない？
なぜ私のアカウントだけ？という疑問はある。

## 可能であれば調べて頂きたいこと

push.hbfav.comがはてブ本体から通知を受け取っていないのか、それ以降のサーバで通知が止まっているのか、調べていただくことは可能でしょうか？

**Comment by naoya** [comment]
調べてみますが、直近なかなか時間がとれないのですこし時間ください。

**Comment by masutaka** [comment]
ありがとうございます！

**Comment by masutaka** [comment]
試しにもう1つWebHookを作り、URLを自分のサーバ宛にしてみました。
しかしNginxのアクセスログを確認しても「お気に入りユーザーによるブックマーク追加」が来ません。。。(自分自身のはてブは来ている模様。)

はてなのサポートに聞いてみますので、ペンディングとさせてください。

**Comment by naoya** [comment]
お、なるほど･･･そんなことが

**Comment by masutaka** [comment]
原因ははっきりしませんが、通知が来るようになりましたのでクローズします。

はてなサポートによると、

> 本件に関しては、お気に入り機能のシステムの一部が過負荷となっていたのを
> 改善したため、その影響で問題が解消された可能性が考えられますが、
> 根本的な原因については調査中となっております。

とのことです。お騒がせしました。
(また通知が来なくなる可能性はありますが、それはそれで。)
