### ISSUE TITLE
動画を再生中にタップするとクラッシュする。

### ISSUE THREAD

**Issue by hururtoriya** [naoya/HBFav2#138]
動画再生中にディスプレイをタップすると、今のところ再現率100%でアプリがクラッシュします。

![](https://lh3.googleusercontent.com/dW2t1DJbKgtZajlFlJpjd4yOryorkzCaTykdl1smoRyyu6a4vHVRsFe9eO2Vugj65GfLQ4J8sYqvOSPzV6izMHfmTnLxb6XIh66iRId_-WmEl4NqC0y4rtfhE-uD7uMLHQCh1tnmqhWfIiE6ucwIKngnGFpKAvAYWzuGRCmkqFBvPUeSJy3CYBcTNd3lQiqtq7jFOi312ddrhq96HZI6Z6xV23Hlm-t8lzHK_zjh9K4851AqfuMVRFozM9v4f0OP_1k3OfrwA7sr0-k6kCuw5YnBk96IiPQe-PEx322aUfgrHDfh1O1VJ42CpiAJLQxHcY71H_kdzyysPdBKeEF4S3S_wgbc4z70xfTJg8CanF744KHoVd2K0sVEtAtbrJ_qH273aULqT6IDbHm3IY-k36gm_kxzZ1CqIluC7jKzZ7ypcXG6kmZdSff4xSyIg0mPaZj7pIrdg9D2Hs2_EbkwxTZwGH_GLUA1bNWGqin8wet6_qUOr-DkMKwUb0mMTE86aNP65nU6z9LEXLI6aCTLByNwnEybheDfGM_wJXR8unlX=w538-h955-no)

検証動画も録ってみました。
https://www.youtube.com/watch?v=YBzYWUNRR8U

動画のビューでタップするとクラッシュするというよりも、動画自体が上手く読み込めてないですね?

**Comment by Watson1978** [comment]
#132 と同じですね :smile:

**Comment by naoya** [comment]
#133 で fix されているので、次のリリースで修正されます。少々お待ち下さいませ

**Comment by hururtoriya** [comment]
確認できてなかったです。 すみません :sweat_smile:

**Comment by naoya** [comment]
あー、いえいえ、わざわざ動画もいただき、報告ありがとうございます！
