### ISSUE TITLE
スプラッシュ画面でのロゴ画像の抜け落ち

### ISSUE THREAD

**Issue by hururtoriya** [naoya/HBFav2#147]

**Comment by hururtoriya** [comment]
![](https://goo.gl/photos/1C8ZWXEdmqVni4VN6)

**Comment by hururtoriya** [comment]
https://goo.gl/photos/Rvtz2f1D835Hnypp7

**Comment by Watson1978** [comment]
再インストールしても状況は変わらないのでしょうか？

**Comment by hururtoriya** [comment]
再インストールし直したところ直りました。
お手間お掛けしました🙇🏼
